### ISSUE TITLE
[PP3] Requirements 

### ISSUE THREAD

**Issue by zsofitoth** [zsofitoth/RAWDATA_Project_Portfolio#29]
# PP3 - Information Retrieval
#### Part 1
- [x] B.1 Basic Boolean retrieval (not FULLTEXT or LIKE) - Zoli
  - create stored procedure
in: keywords [1, 2, ..., n]
out: posts that match all of these
  - approach: inverted index 
  - merging postings list
- [x] B.2: Best Match - Zoli
  -  refine B.1
  - "best-match" ranking and ordering = the more keywords that match the higher the rank is
  - introduce term frequency [ n(t) ] (how many times a term occurs in a document)
- [x] B.3: Weighted Indexing - Zoli
  - build new inverted index, similar to B.1, but now with added weights to postings
  - variant of TF-IDF
  - consider normalization
  - consider stopwords
- [x] B.4: Use Weighted Indexing - Zoli
  - refine procedure in B.2 to use ranking and new inverted index developed in B.3
#### Part 2
- [x] B.5: Weighted Keyword Lists **(Document Frequency [ n(t) ])** - Zsofi
0. create a stored procedure 
in: keyword / keywords / phrase (?)
out: weighted keywords list
1. evaluate the keyword query and derive the set of all matching posts
2. count word frequencies over all matching posts
3. provide the most frequent words as an answer ( descending order ) ( frequency is the weight )
- [x] B.6: Weighted Keyword Lists **(TF-IDF )** - Zsofi
  - based on sum of weights, not frequencies
  - TF(d,t) = log(1 + n(d,t)/n(d))
- [X] B.7: Visualize Weighted Keyword Lists - Zsofi
  - use [tool](http://mistic100.github.io/jQCloud/index.html)
- [x] B.8: Co-occurence Term Network - Zsofi
  - table of two word combination 
  - include weights about how often the two terms co-occur
  - weight = count of co-occurences in all posts
  - create a procedure 
  - see notes at **assoc** table in #30 
in: word/keyword
out: closest terms in decreasing order
- [x] B.9: Visualize Co-occurence Term Network/Force Networks - Zsofi
  - use [tool](https://moodle.ruc.dk/mod/page/view.php?id=161964)
### Indexing
- [x] C.1: Indexing of Database - Zoli
- [x] C.2: Performance - Zoli
  - discuss/explain what is needed to obtain an acceptable performance when dealing with inverted index, weighting and term networks.
### Backend
-  Accessing stored procedures through entity framework
  - [x] B.4 - best match
  - [x] B.5 - weighted keywords list
  - [x] B.8 - co-occurence
  - [x] tag assoc
- [ ] Cleansing input from user
### Testing
- [X] Black Box Testing - Zsofi + Zoli
## Report 
- Zsofi
- #30 Schema
- [X] Finish it

**w(t)** - _sum of term relevance all over the document_
   - w(t) = Σ r(d, t) where d∈D (D = set of documents) and is **r(d,t)** the _relevance of document to term t_
   - r(d, t) = TF(d,t) * IDF(t) where **TF** is _term frequency_ and **IDF** is _inverted document frequency_
   - TF(d,t) = log(1 + n(d,t)/n(d)) where **n(d,t)** is the _number of occurrences of term t in document d_ and **n(d)** is the _number of terms in document d_
   - IDF(t) = 1/n(t) where **n(t)** is the _number of documents that contain the term t_
