### ISSUE TITLE
Data Layer

### ISSUE THREAD

**Issue by zsofitoth** [zsofitoth/RAWDATA_Project_Portfolio#4]
**Design Patterns**
- [X] Repository Pattern
- [X] Singleton
-  Facade
-  Factory
-  Potential Business Layer
- [ ] Refactoring 
   - [ ] Duplicate query logic
   - [ ] DTOs where needed on service layer

**Todo**
- [X] Implement Q&A user stories on the data layer
- [ ] Implement H&M user stories on the data layer
